[MAPA-63] - Hotfix therapist form
mapadoacolhimento/cadastro pull request #61
Opened 2024-01-19 15:04 UTC by dieh

Conforme o teste realizado em 16/01 o cadastro está apresentando erros nas etapas mostrando informações de advogada. Atrávés de teste descobrimos que ao se cadastrar como advogada e depois voltar e se cadastrar como psicóloga as opções de advogada do form se mantinham. Assim,  removi os defaults de campos que estavam como de psicóloga para setar sempre que for escolhido passo.

2024-01-19 16:02 UTC, vivianedias requested changes
só remover os logs, de resto tá show! ✨

2024-01-19 16:02 UTC, vivianedias commented on volunteers/views.py
> +logging.basicConfig(format="%(levelname)s:%(message)s", level=logging.DEBUG)
```suggestion
```

2024-01-19 16:02 UTC, vivianedias commented on volunteers/views.py
> +        )
```suggestion
```

2024-01-19 16:02 UTC, vivianedias commented on volunteers/views.py
> +    logging.info(f"Type form: {type_form}, step: {step}")
```suggestion
```

2024-01-19 17:02 UTC, gloriateodoro approved these changes

2024-01-21 22:39 UTC, vivianedias approved these changes

2024-01-21 22:39 UTC, merged