[MAPA-131]  create send_welcome_email to volunteers
mapadoacolhimento/cadastro pull request #64
Opened 2024-01-25 15:18 UTC by dieh

2024-01-26 14:52 UTC, vivianedias requested changes
perf ✨ bora mandar esse email!!

2024-01-26 14:52 UTC, vivianedias commented on volunteers/utils.py
> +    )
recebi o e-mail lindinho, porém, precisamos configurar o "sender name", que é o nome que aparece lá na caixa de inbox e hoje está só  "voluntaria".

ideal seria "Equipe do Mapa do Acolhimento".

vi nesse stack overflow como faz: https://stackoverflow.com/questions/67968102/sender-name-in-sendgrid-python-package

2024-01-29 13:24 UTC, dieh commented on volunteers/utils.py
> +    )
@vivianedias boa! Revisões feitas

2024-01-29 14:09 UTC, vivianedias approved these changes
💅🏾

2024-01-29 14:09 UTC, merged