[MAPA-182] - Feature/creates volunteer zendesk
mapadoacolhimento/cadastro pull request #80
Opened 2024-04-04 20:17 UTC by dieh

2024-04-10 13:45 UTC, vivianedias requested changes

2024-04-10 13:45 UTC, vivianedias commented on volunteers/te.json
precisamos desse arquivo?

2024-04-10 13:45 UTC, vivianedias commented on volunteers/views.py
> +           volunteer.save()
vamos fazer esse tratamento buscando o `zendesk_user_id` na response direto no `create_zendesk_user`

ai aqui so precisamos fazer:

```
volunteer_zendesk_user_id = create_zendesk_user(form_data.values, form_data.type_form, volunteer.condition)
volunteer.zendesk_user_id = volunteer_zendesk_user_id
volunteer.save()
```

2024-04-10 13:45 UTC, vivianedias commented on volunteers/zendesk.py
> +        print(f"payload: {json_payload}")
```suggestion
```

2024-04-10 13:45 UTC, vivianedias commented on volunteers/zendesk.py
> +            print({"data": response.json()})
```suggestion
```

2024-04-10 13:45 UTC, vivianedias commented on volunteers/zendesk.py
> +            return JsonResponse({"data": response.json()})
aqui podemos retornar direto o `user_id`

2024-04-10 13:45 UTC, vivianedias commented on volunteers/zendesk.py
> +            return JsonResponse(
aqui podemos retornar direto `null`

e logar o erro apenas, inves de colocar em um JsonResponse

2024-04-10 13:52 UTC, dieh commented on volunteers/te.json
não rs

2024-04-14 13:31 UTC, vivianedias approved these changes
💯

2024-04-14 13:31 UTC, vivianedias commented on volunteers/models.py
> +    internal_id = models.BigIntegerField(blank=True, null=True)
👍🏾

2024-04-14 13:46 UTC, merged